# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077f2a941b63802ab903b8d3b2d2d4f51d177e22b504eadc224ed5096d82c0b450638bc0b12cba32af271741aaf3db79d3e01294887513b9649598773e7c1949

test:
  secret_key_base: 4e24fba8dec0da22d3c78006b80fa2df478e4f7b7d211a17cbd39a721c02d003e3a92d36fd871d6ce565286748dfe2713094fb24ed4b6a6ff36b445c2dabf012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
